/*
 *   Copyright (c) 2020 Orfeo da Vià
 *
 *   Boost Software License - Version 1.0 - August 17th, 2003
 *
 *   Permission is hereby granted, free of charge, to any person or organization
 *   obtaining a copy of the software and accompanying documentation covered by
 *   this license (the "Software") to use, reproduce, display, distribute,
 *   execute, and transmit the Software, and to prepare derivative works of the
 *   Software, and to permit third-parties to whom the Software is furnished to
 *   do so, all subject to the following:
 *
 *   The copyright notices in the Software and this entire statement, including
 *   the above license grant, this restriction and the following disclaimer,
 *   must be included in all copies of the Software, in whole or in part, and
 *   all derivative works of the Software, unless such copies or derivative
 *   works are solely in the form of machine-executable object code generated by
 *   a source language processor.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *   DEALINGS IN THE SOFTWARE.
 */

module app;

import std.stdio;
import std.process : execute;
import std.experimental.logger;

enum MIRROR = "./.mirror";

string getFolderName(string name, string v) {
   import std.path : buildPath;

   return buildPath(MIRROR, name ~ "-" ~ v);
}

unittest {
   string f = getFolderName("cul", "0.1.0");
   assert(f == "./.mirror/cul-0.1.0", f);
}

string[] getCloneCmd(string url, string branch, string folder) {
   string[] a = ["git", "clone", "--depth", "1"];
   a ~= "--branch";
   a ~= "v" ~ branch;
   a ~= url;
   a ~= folder;

   return a;
}

unittest {
   string[] x = getCloneCmd("git@o30", "0.13.0", "cul");
   assert(x[0] == "git");
   assert(x[5] == "v0.13.0");
}

void run(bool clean) {
   import std.array : join;
   import std.file : readText, exists, mkdirRecurse, rmdirRecurse;
   import std.string : startsWith;
   import std.json : parseJSON, JSONValue;

   string depJ = readText("localdep.json");
   JSONValue dubConfig = parseJSON(depJ);

   foreach (dep; dubConfig.array) {
      writeln(dep["name"].get!string);
      string v = dep["version"].get!string;
      if (v.startsWith("v")) {
         v = v[1 .. $];
      }

      string f = getFolderName(dep["name"].get!string, v);
      if (clean) {
         tracef("Remove %s dir", f);
         f.rmdirRecurse;
         return;
      }

      if (!exists(f)) {
         f.mkdirRecurse;

         string[] cmd = getCloneCmd(dep["url"].get!string, v, f);
         trace(cmd.join(" "));
         auto reply = execute(cmd);
         if (reply.status != 0) {
            errorf("Failed\n", reply.output);
         } else {
            info("Successful");
         }
      }
   }
}

void main(string[] args) {
   import std.getopt;

   bool verbose;
   bool clean;

   auto opt = getopt(args, "verbose|v", "Verbose", &verbose, "clean|c", "Delete package directory", &clean);
   if (verbose) {
      globalLogLevel(LogLevel.trace);
   } else {
      globalLogLevel(LogLevel.error);
   }
   if (opt.helpWanted) {
      defaultGetoptPrinter("dirimere", opt.options);
      help;
   } else {
      run(clean);
   }
}

void help() {
}
